// Generated by @wiscaksono/sveltekit-route-intercept/vite
// Do not edit manually.

import { createKitInterceptor, type CreateKitInterceptorConfig, type CreateKitInterceptorJsonConfig, type JsonValue } from '@wiscaksono/sveltekit-route-intercept';

export const interceptors = {
	photo: (config: Omit<CreateKitInterceptorJsonConfig<'photo', '/photos/[id]'>, 'key' | 'route'> = {}) =>
		createKitInterceptor<'photo', '/photos/[id]'>({
			...config,
			key: 'photo',
			route: '/photos/[id]'
		}),
	photoTyped: <TPayload extends JsonValue>(config: Omit<CreateKitInterceptorConfig<'photo', '/photos/[id]', TPayload>, 'key' | 'route'>) =>
		createKitInterceptor<'photo', '/photos/[id]', TPayload>({
			...config,
			key: 'photo',
			route: '/photos/[id]'
		})
} as const;
