// Generated by @wiscaksono/sveltekit-route-intercept/vite
// Do not edit manually.

import type { RouteParamsFromPath } from '@wiscaksono/sveltekit-route-intercept';

export type InterceptKeys = 'photo';

export type InterceptRouteMap = {
	'photo': '/photos/[id]';
};

export type InterceptParams<K extends InterceptKeys> = RouteParamsFromPath<InterceptRouteMap[K]>;

declare global {
	namespace App {
		interface PageState {
			__routeIntercept?: {
			'photo'?: unknown;
			};
		}
	}
}

export {};
