/**
 * Primitive JSON value types.
 */
export type Primitive = string | number | boolean | null;

/**
 * JSON-compatible value used for intercepted payloads.
 *
 * @remarks
 * Payloads are stored in `history.state`, so values must be JSON-safe.
 */
export type JsonValue = Primitive | JsonValue[] | { [key: string]: JsonValue };

/**
 * Runtime shape for route parameters accepted by href builders.
 */
export type RouteParams = Record<string, string | number | string[]>;

type Merge<T> = { [K in keyof T]: T[K] };
type SegmentParam<S extends string> = S extends `[[...${infer P}]]`
	? P
	: S extends `[...${infer P}]`
		? P
		: S extends `[${infer P}]`
			? P
			: never;
type SegmentValue<S extends string> = S extends `[[...${string}]]`
	? string[]
	: S extends `[...${string}]`
		? string[]
		: string;
type SegmentOptional<S extends string> = S extends `[[...${string}]]` ? true : false;
type AddParam<Name extends string, Value, Optional extends boolean> = [Name] extends [never]
	? {}
	: Name extends ''
		? {}
		: Optional extends true
			? { [K in Name]?: Value }
			: { [K in Name]: Value };

/**
 * Infers route parameter object type from a SvelteKit route template.
 *
 * @example
 * ```ts
 * type A = RouteParamsFromPath<'/photos/[id]'>;
 * //   ^? { id: string }
 *
 * type B = RouteParamsFromPath<'/docs/[[...slug]]'>;
 * //   ^? { slug?: string[] }
 * ```
 */
export type RouteParamsFromPath<Path extends string> = Path extends `${infer Head}/${infer Tail}`
	? Merge<RouteParamsFromPath<Head> & RouteParamsFromPath<Tail>>
	: Path extends ''
		? {}
		: AddParam<SegmentParam<Path>, SegmentValue<Path>, SegmentOptional<Path>>;

/**
 * Page state extension used to persist intercepted payloads in history state.
 */
export type InterceptPageState<Map extends Record<string, JsonValue> = Record<string, JsonValue>> = {
	__routeIntercept?: Partial<Map>;
};

/**
 * A value that can be returned synchronously or asynchronously.
 */
export type MaybePromise<T> = T | Promise<T>;

/**
 * Result returned by `preloadData` for successfully loaded routes.
 */
export type LoadedResult = {
	type: 'loaded';
	status: number;
	data: Record<string, unknown>;
};

/**
 * Result returned by `preloadData` for redirect responses.
 */
export type RedirectResult = {
	type: 'redirect';
	location: string;
};

/**
 * Union of all preload outcomes needed by interceptor navigation.
 */
export type PreloadResult = LoadedResult | RedirectResult;

/**
 * Outcome of trying to open an intercepted route.
 */
export type OpenResult<TPayload> =
	| { type: 'intercepted'; href: string; payload: TPayload }
	| { type: 'redirected'; location: string }
	| { type: 'navigated'; href: string }
	| { type: 'bypassed'; href: string };

/**
 * Navigation dependencies used by `createInterceptor`.
 *
 * @typeParam TPageState - Concrete page state object used by the app.
 */
export type NavigationDeps<TPageState extends Record<string, unknown>> = {
	preloadData: (href: string) => Promise<PreloadResult>;
	pushState: (url: string, state: TPageState) => void;
	goto: (url: string) => MaybePromise<void>;
	getState: () => TPageState;
	resolveHref?: (href: string) => string;
	allowIntercept?: (event: MouseEvent) => boolean;
	handleRedirect?: (location: string) => MaybePromise<void>;
};

/**
 * Typed interceptor definition shared across runtime helpers.
 *
 * @typeParam TKey - Stable key used to store payload in page state.
 * @typeParam TRoute - Route template like `/photos/[id]`.
 * @typeParam TParams - Inferred route parameter shape.
 * @typeParam TPayload - Payload accepted by `parsePayload`.
 */
export type InterceptDefinition<
	TKey extends string,
	TRoute extends string,
	TParams extends RouteParams,
	TPayload extends JsonValue
> = {
	readonly key: TKey;
	readonly route: TRoute;
	readonly href: (params: TParams) => string;
	readonly parsePayload: (value: unknown) => value is TPayload;
};

/**
 * Options passed to click handlers generated by an interceptor.
 */
export type ClickOptions<TParams extends RouteParams> = {
	params: TParams;
	href?: string;
};

const isPlainRecord = (value: object): value is Record<string, unknown> => {
	const prototype = Object.getPrototypeOf(value);
	return prototype === Object.prototype || prototype === null;
};

const isJsonValueInternal = (value: unknown, seen: WeakSet<object>): value is JsonValue => {
	if (value === null) return true;

	const primitiveType = typeof value;
	if (primitiveType === 'string' || primitiveType === 'number' || primitiveType === 'boolean') {
		return true;
	}

	if (primitiveType !== 'object') {
		return false;
	}

	if (!value) {
		return false;
	}

	if (seen.has(value)) {
		return false;
	}

	seen.add(value);

	if (Array.isArray(value)) {
		for (const item of value) {
			if (!isJsonValueInternal(item, seen)) {
				return false;
			}
		}

		return true;
	}

	if (!isPlainRecord(value)) {
		return false;
	}

	for (const item of Object.values(value)) {
		if (!isJsonValueInternal(item, seen)) {
			return false;
		}
	}

	return true;
};

/**
 * Checks whether a value is JSON-compatible.
 *
 * @remarks
 * Returns `false` for non-plain objects, functions, symbols, bigint values,
 * and cyclic structures.
 */
export const isJsonValue = (value: unknown): value is JsonValue => {
	return isJsonValueInternal(value, new WeakSet<object>());
};
